version: '3.7'

services:
  db:
    image: pverscha/unipept-database:1.0.2
    environment:
      MYSQL_ROOT_PASSWORD: unipept
      MYSQL_DATABASE: unipept
      MYSQL_USER: unipept
      MYSQL_PASSWORD: unipept
      DB_TYPES: swissprot
      DB_SOURCES: https://ftp.expasy.org/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.xml.gz
      FILTER_TAXA: 1
      VERBOSE: true
    restart: always
    ports:
      - "3306:3306"
    hostname: mysql
    volumes:
      # Volume that's being used to store the MySQL-database data. This directory can contain quite a lot of data!
      - type: bind
        # Change this to a folder on you hard drive where you want the actual database to be stored.
        source: /Users/pverscha/Desktop/dbs/outputs/db_swissprot
        target: /var/lib/mysql
      # Volume that's being used to store the Unipept index. This index is a special kind of structure that can easily
      # be queried and filtered by taxa (if required). The index will be created on first run of an image (if it is
      # not yet present in the folder that's mounted) and will greatly increase the build speed of the database.
      - type: bind
        # Change this to a folder on your hard drive where the Unipept index could be stored.
        source: /Users/pverscha/Desktop/dbs/index
        target: /index
      - type: bind
        source: /tmp
        target: /tmp
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: unipept
    restart: always
