#! /bin/bash

# Exit immediately when an error occurs
set -e
# Exit when a command in one of the pipelines fails
set -o pipefail

# This command should produce tsv.gz files that can later on be inserted into the database.
cd "/make-database"
echo "unipept" | su -c "./scripts/build_database.sh -f $FILTER_TAXA -i '/index'  -d '/tmp' database $DB_TYPES $DB_SOURCES '/tables'" root

echo "***** START LOADING TABLES *****"

# Data has been generated by this point. Now, we can load it into the MySQL-database for use later on.
mysql -uunipept -punipept < schemas/structure_no_index.sql
echo "unipept" | su -c "./scripts/load.sh '/tables'" root
rm '/tables/**/*.tsv.gz'

echo "***** START INDEXING TABLES *****"

echo "unipept" | su -c "./scripts/index.sh" root
